# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            42
tagline:          'Socialmetrix DevBlog'
url:              http://hyde.getpoole.com

author:
  name:           'Socialmetrix'
  url:            https://twitter.com/socialmetrix

paginate:         10

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
