# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            42
tagline:          'Socialmetrix DevBlog'
description:	  'Socialmetrix DevBlog'
url:              http://42.smx.io

author:
  name:           'Socialmetrix'
  url:            https://twitter.com/socialmetrix

paginate:         10
